Repository nextcloud/survey_client, pull requests merged in 2018-08, with the labels that each got.

#77 enable survey client by default
  appinfo/info.xml
Labels: 3. to review, bug

#72 Move over to OCSController
  appinfo/routes.php
  lib/AppInfo/Application.php
  lib/Collector.php
  lib/Controller/EndpointController.php
Labels: 3. to review, enhancement

#79 Change description into a sentence
  lib/Categories/Stats.php
Labels: 3. to review
