Repository nextcloud/survey_client, pull requests merged in 2024-07, with the labels that each got.

#298 Add SPDX header
  .github/contributing.md
  .github/dependabot.yml
  .github/issue_template.md.license
  .github/workflows/block-merge-freeze.yml
  .github/workflows/lint-info-xml.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/psalm.yml
  .github/workflows/reuse.yml
  .github/workflows/update-nextcloud-ocp.yml
  .gitignore
  .php-cs-fixer.dist.php
  .reuse/dep5
  AUTHORS.md
  LICENSES/AGPL-3.0-only.txt
  LICENSES/AGPL-3.0-or-later.txt
  LICENSES/Apache-2.0.txt
  LICENSES/CC0-1.0.txt
  LICENSES/MIT.txt
  README.md
  appinfo/info.xml
  appinfo/routes.php
  css/admin.css
  img/app-dark.svg
  img/app.svg
  js/admin.js
  lib/AppInfo/Application.php
  lib/BackgroundJobs/AdminNotification.php
  lib/BackgroundJobs/MonthlyReport.php
  lib/Categories/Apps.php
  lib/Categories/Database.php
  lib/Categories/Encryption.php
  lib/Categories/FilesSharing.php
  lib/Categories/ICategory.php
  lib/Categories/Php.php
  lib/Categories/Server.php
  lib/Categories/Stats.php
  lib/Collector.php
  lib/Controller/EndpointController.php
  lib/Migration/SendAdminNotification.php
  lib/Notifier.php
  lib/Settings/AdminSection.php
  lib/Settings/AdminSettings.php
  psalm.xml.license
  templates/admin.php
Labels: 3. to review, technical debt

#224 chore: update workflows from templates
  .github/workflows/block-merge-freeze.yml
  .github/workflows/lint-info-xml.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/psalm.yml
  .github/workflows/update-nextcloud-ocp.yml
Labels: 3. to review, dependencies, automated

#284 [stable27] Update nextcloud/ocp dependency
  .github/workflows/phpunit-sqlite.yml
  composer.json
  composer.lock
  lib/AppInfo/Application.php
  lib/BackgroundJobs/AdminNotification.php
  lib/BackgroundJobs/MonthlyReport.php
  lib/Categories/Database.php
  lib/Controller/EndpointController.php
  lib/Migration/SendAdminNotification.php
  lib/Settings/AdminSettings.php
  templates/admin.php
Labels: 3. to review, dependencies

#296 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#297 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#292 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#225 [stable28] chore: update workflows from templates
  .github/workflows/block-merge-freeze.yml
  .github/workflows/dependabot-approve-merge.yml
  .github/workflows/lint-info-xml.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/pr-feedback.yml
  .github/workflows/psalm.yml
  .github/workflows/update-nextcloud-ocp.yml
  composer.json
Labels: 3. to review, dependencies, automated

#299 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies
