Repository nextcloud/survey_client, pull requests merged in 2024-06, with the labels that each got.

#291 feat: update dependency on branch stable28
  .github/workflows/phpunit-sqlite.yml
  composer.json
  composer.lock
  lib/AppInfo/Application.php
  lib/BackgroundJobs/AdminNotification.php
  lib/BackgroundJobs/MonthlyReport.php
  lib/Categories/Database.php
  lib/Controller/EndpointController.php
  lib/Migration/SendAdminNotification.php
  lib/Settings/AdminSettings.php
  templates/admin.php
Labels: 3. to review

#281 [stable29] Update nextcloud/ocp dependency
  composer.json
  composer.lock
Labels: 3. to review, dependencies

#283 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#293 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#273 chore(CI): Updating pr-feedback.yml workflow from template
  .github/workflows/pr-feedback.yml
Labels: dependencies

#274 Updating dependabot-approve-merge.yml workflow from template
  .github/workflows/dependabot-approve-merge.yml
Labels: dependencies

#295 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies
