Repository nextcloud/survey_client, pull requests merged in 2024-09, with the labels that each got.

#310 chore(CI): Updating dependabot-approve-merge.yml workflow from template
  .github/workflows/dependabot-approve-merge.yml
Labels: dependencies

#300 chore: update workflows from templates
  .github/workflows/block-merge-freeze.yml
  .github/workflows/lint-info-xml.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/pr-feedback.yml
  .github/workflows/psalm.yml
  .github/workflows/reuse.yml
  .github/workflows/update-nextcloud-ocp.yml
Labels: 3. to review, dependencies, automated

#311 Migrate REUSE: dep5 to toml format
  .reuse/dep5
  REUSE.toml
Labels: 4. to release

#314 fix: failure when using sqlite3
  lib/Categories/Database.php
Labels: bug, 3. to review, backport-request

#315 fix: clarify language for removing previously sent report data
  templates/admin.php
Labels: bug, 3. to review, backport-request

#317 fix: notifications link for mobile / desktop error generating errors in v30
  lib/BackgroundJobs/AdminNotification.php
Labels: bug, 3. to review, backport-request

#327 fix(notifications): Only define URLs and actions in one place
  lib/BackgroundJobs/AdminNotification.php
  lib/Notifier.php
  psalm.xml
Labels: 3. to review, backport-request
